apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.Namespace }}
  name: application
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  LIBRENMS_MYSQL_DATABASE: librenms
  LIBRENMS_BASE_URL: {{ .Values.IngressURL }}
  LIBRENMS_ADMINISTRATIVE_ADDRESSES: {{ .Values.AdministrativeAddresses | default "" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.Namespace }}
  name: dispatcher
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  LIBRENMS_DISPATCHER_POLLER_WORKERS: "24"
  LIBRENMS_DISPATCHER_DISCOVERY_WORKERS: "16"
  LIBRENMS_DISPATCHER_SERVICES_WORKERS: "8"
  LIBRENMS_DISPATCHER_LOG_LEVEL: -v
