apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.Namespace }}
  name: application
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  LIBRENMS_MYSQL_DATABASE: "librenms"
  LIBRENMS_MEMORY_LIMIT: {{ .Values.Application.memoryLimit | quote }}
  LIBRENMS_BASE_URL: {{ .Values.Application.baseURL | quote }}
  LIBRENMS_SNMP_RTT: {{ .Values.Application.snmpRTT | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.Namespace }}
  name: dispatcher
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  LIBRENMS_DISPATCHER_POLLER_WORKERS: {{ .Values.Dispatcher.pollerWorkers | quote }}
  LIBRENMS_DISPATCHER_DISCOVERY_WORKERS: {{ .Values.Dispatcher.discoveryWorkers | quote }}
  LIBRENMS_DISPATCHER_SERVICES_WORKERS: {{ .Values.Dispatcher.serviceWorkers | quote }}
  LIBRENMS_DISPATCHER_LOG_LEVEL: {{ .Values.Dispatcher.logLevel | quote }}
