apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespace }}
  name: dispatcher
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.Namespace }}
  name: dispatcher
  labels:
    application: librenms
spec:
  serviceName: dispatcher
  selector:
    matchLabels:
      component: dispatcher
  replicas: {{ .Values.DispatcherCount }}
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      name: dispatcher
      labels:
        application: librenms
        component: dispatcher
    spec:
      initContainers:
      - name: check-mysql
        image: docker.io/tpboudreau/librenms-check-mysql:0.1
        envFrom:
        - configMapRef:
            name: application
        env:
        - name: LIBRENMS_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_user
        - name: LIBRENMS_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_password
      - name: check-rrdcached
        image: docker.io/tpboudreau/librenms-check-rrdcached:0.1
        envFrom:
        - configMapRef:
            name: application
      - name: check-memcached
        image: docker.io/tpboudreau/librenms-check-memcached:0.1
        envFrom:
        - configMapRef:
            name: application
      - name: check-redis
        image: docker.io/tpboudreau/librenms-check-redis:0.1
        envFrom:
        - configMapRef:
            name: application
        env:
        - name: LIBRENMS_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_redis_password
      containers:
      - name: dispatcher
        image: docker.io/tpboudreau/librenms-dispatcher:0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: application
        - configMapRef:
            name: dispatcher
        env:
        - name: LIBRENMS_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_user
        - name: LIBRENMS_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_password
        - name: LIBRENMS_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_redis_password
        - name: LIBRENMS_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_application_key
