
credentials:
  application:
    administrativeUser:
    administrativePassword:
    administrativeEmail:
    key:
  mysql:
    rootPassword:
    user:
    password:
  redis:
    password:
  
Application:
  serviceType: cluster
  servicePath: "/"
  servicePort: 80
  providerPort: 8000
  baseURL:
  memoryLimit: 1024
  prepareVolumeImage:
    repository: "docker.io/tpboudreau/librenms-application-prepare-volume"
    tag: "0.1"
  phpImage:
    repository: "docker.io/tpboudreau/librenms-application-php-fpm"
    tag: "0.1"
  nginxImage:
    repository: "docker.io/tpboudreau/librenms-application-nginx"
    tag: "0.1"
  replicas: 1

Dispatcher:
  instances: 4
  pollerWorkers: 24
  discoveryWorkers: 16
  serviceWorkers: 8
  logLevel: "-v"
  image:
    repository: "docker.io/tpboudreau/librenms-dispatcher"
    tag: "0.1"

snmpPing:
  enabled: false
  recordRTT: true

checkMySQL:
  image:
    repository: "docker.io/tpboudreau/librenms-check-mysql"
    tag: "0.1"

checkRRDcached:
  image:
    repository: "docker.io/tpboudreau/librenms-check-rrdcached"
    tag: "0.1"

checkMemcached:
  image:
    repository: "docker.io/tpboudreau/librenms-check-memcached"
    tag: "0.1"

checkRedis:
  image:
    repository: "docker.io/tpboudreau/librenms-check-redis"
    tag: "0.1"

cleanupApplication:
  image:
    repository: "docker.io/tpboudreau/librenms-cleanup-application"
    tag: "0.1"

