
Application:
  serviceType: ingress
  ingressHost: "librenms.example.com"

credentials:
  application:
    administrativeUser: "admin"
    administrativePassword: "adminPassword"
    administrativeEmail: "admin@example.org"
  mysql:
    rootPassword: "mysqlRootPassword"
    user: "librenms"
    password: "userPassword"
  redis:
    password: "redisPassword"

