apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  type: ClusterIP
  selector:
    component: memcached
  ports:
  - name: memcached
    port: 11211
    targetPort: memcached
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  labels:
    application: librenms
spec:
  serviceName: memcached
  selector:
    matchLabels:
      component: memcached
  replicas: 1
  template:
    metadata:
      name: memcached
      labels:
        application: librenms
        component: memcached
    spec:
      containers:
      - name: memcached
        image: docker.io/tpboudreau/librenms-memcached:0.1
        envFrom:
          - configMapRef:
              name: memcached
        ports:
        - name: memcached
          containerPort: 11211
          protocol: TCP
