apiVersion: v1
kind: Pod
metadata:
  name: default-dispatcher
  labels:
    application: librenms
    component: dispatcher
spec:
  initContainers:
  - name: mysql-checker
    image: docker.io/tpboudreau/librenms-check-mysql
    envFrom:
    - configMapRef:
        name: application
    env:
    - name: LIBRENMS_MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_mysql_user
    - name: LIBRENMS_MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_mysql_password
  - name: rrdcached-checker
    image: docker.io/tpboudreau/librenms-check-rrdcached
    envFrom:
    - configMapRef:
        name: application
  - name: memcached-checker
    image: docker.io/tpboudreau/librenms-check-memcached
    envFrom:
    - configMapRef:
        name: application
  - name: redis-checker
    image: docker.io/tpboudreau/librenms-check-redis
    envFrom:
    - configMapRef:
        name: application
    env:
    - name: LIBRENMS_REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_redis_password
  containers:
  - name: dispatcher
    image: docker.io/tpboudreau/librenms-dispatcher
    envFrom:
    - configMapRef:
        name: application
    - configMapRef:
        name: default-dispatcher
    env:
    - name: LIBRENMS_MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_mysql_user
    - name: LIBRENMS_MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_mysql_password
    - name: LIBRENMS_REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_redis_password
    - name: LIBRENMS_APPLICATION_KEY
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_application_key
