apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    application: librenms
    component: redis
spec:
  containers:
  - name: redis-provider
    image: docker.io/tpboudreau/librenms-redis
    envFrom:
    - configMapRef:
        name: redis
    env:
    - name: REDIS_REQUIRED_PASSWORD
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_redis_password
    volumeMounts:
    - name: redis-volume
      subPath: data
      mountPath: /data
    - name: redis-socket
      mountPath: /sock
  - name: redis-controller
    image: docker.io/tpboudreau/librenms-controller
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
    envFrom:
    - configMapRef:
        name: controller
    - configMapRef:
        name: controller-redis
    volumeMounts:
    - name: redis-socket
      mountPath: /sock
    ports:
    - name: redis
      containerPort: 36379
      protocol: TCP
  volumes:
  - name: redis-volume
    persistentVolumeClaim:
      claimName: redis-volume
  - name: redis-socket
    emptyDir:
      medium: Memory
