apiVersion: v1
kind: Pod
metadata:
  name: rrdcached
  labels:
    application: librenms
    component: rrdcached
spec:
  containers:
  - name: rrdcached-provider
    image: docker.io/tpboudreau/librenms-rrdcached
    envFrom:
    - configMapRef:
        name: rrdcached
    volumeMounts:
    - name: rrdcached-volume
      subPath: data
      mountPath: /rrd/data
    - name: rrdcached-volume
      subPath: journal
      mountPath: /rrd/journal
    - name: rrdcached-socket
      mountPath: /sock
  - name: rrdcached-controller
    image: docker.io/tpboudreau/librenms-controller
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
    envFrom:
    - configMapRef:
        name: controller
    - configMapRef:
        name: controller-rrdcached
    volumeMounts:
    - name: rrdcached-socket
      mountPath: /sock
    ports:
    - name: rrdcached
      containerPort: 42217
      protocol: TCP
  volumes:
  - name: rrdcached-volume
    persistentVolumeClaim:
      claimName: rrdcached-volume
  - name: rrdcached-socket
    emptyDir:
      medium: Memory
