apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: ClusterIP
  selector:
    component: application
  ports:
  - name: application
    port: 80
    targetPort: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    application: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      component: application
  template:
    metadata:
      name: application
      labels:
        application: librenms
        component: application
    spec:
      initContainers:
      - name: application-prepare-volume
        image: docker.io/tpboudreau/librenms-application-prepare-volume:0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: application
        env:
        - name: LIBRENMS_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_user
        - name: LIBRENMS_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_password
        - name: LIBRENMS_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_redis_password
        - name: LIBRENMS_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_application_key
        volumeMounts:
        - name: application-volume
          mountPath: /opt/librenms
      - name: check-mysql
        image: docker.io/tpboudreau/librenms-check-mysql:0.1
        envFrom:
        - configMapRef:
            name: application
        env:
        - name: LIBRENMS_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_user
        - name: LIBRENMS_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_mysql_password
      - name: check-rrdcached
        image: docker.io/tpboudreau/librenms-check-rrdcached:0.1
        envFrom:
        - configMapRef:
            name: application
      - name: check-memcached
        image: docker.io/tpboudreau/librenms-check-memcached:0.1
        envFrom:
        - configMapRef:
            name: application
      - name: check-redis
        image: docker.io/tpboudreau/librenms-check-redis:0.1
        envFrom:
        - configMapRef:
            name: application
        env:
        - name: LIBRENMS_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_redis_password
      containers:
      - name: application-php-fpm
        image: docker.io/tpboudreau/librenms-application-php-fpm:0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: application
        volumeMounts:
        - name: application-volume
          mountPath: /opt/librenms
        - name: application-socket
          mountPath: /sock
      - name: application-nginx
        image: docker.io/tpboudreau/librenms-application-nginx:0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: application
        volumeMounts:
        - name: application-volume
          mountPath: /opt/librenms
        - name: application-socket
          mountPath: /sock
        ports:
        - name: application
          containerPort: 8000
          protocol: TCP
      volumes:
      - name: application-volume
        emptyDir: {}
      - name: application-socket
        emptyDir:
          medium: Memory
