apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      forProvider: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrdcached-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      forProvider: rrdcached
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      forProvider: redis
