apiVersion: v1
kind: Pod
metadata:
  name: test-console
  labels:
    application: librenms
    component: test-console
spec:
  containers:
  - name: console
    image: docker.io/tpboudreau/librenms-console
