apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespace }}
  name: rrdcached
spec:
  type: ClusterIP
  selector:
    component: rrdcached
  ports:
  - name: rrdcached
    port: {{ .Values.rrdcached.servicePort }}
    targetPort: rrdcached
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.Namespace }}
  name: rrdcached
  labels:
    application: librenms
spec:
  serviceName: rrdcached
  selector:
    matchLabels:
      component: rrdcached
  replicas: 1
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      name: rrdcached
      labels:
        application: librenms
        component: rrdcached
    spec:
      containers:
      - name: rrdcached
        image: {{ .Values.rrdcached.image.repository }}:{{ .Values.rrdcached.image.tag }}
        envFrom:
        - configMapRef:
            name: rrdcached
        volumeMounts:
        - name: rrdcached-volume
          subPath: data
          mountPath: /data
        - name: rrdcached-volume
          subPath: journal
          mountPath: /journal
        ports:
        - name: rrdcached
          containerPort: {{ .Values.rrdcached.providerPort }}
          protocol: TCP
      volumes:
      - name: rrdcached-volume
        emptyDir: {}
