apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    application: librenms
    component: memcached
spec:
  containers:
  - name: memcached-provider
    image: docker.io/tpboudreau/librenms-memcached
    envFrom:
      - configMapRef:
          name: memcached
    volumeMounts:
    - name: memcached-socket
      mountPath: /sock
  - name: memcached-controller
    image: docker.io/tpboudreau/librenms-controller
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
    envFrom:
    - configMapRef:
        name: controller
    - configMapRef:
        name: controller-memcached
    volumeMounts:
    - name: memcached-socket
      mountPath: /sock
    ports:
    - name: memcached
      containerPort: 11211
      protocol: TCP
  volumes:
  - name: memcached-socket
    emptyDir:
      medium: Memory
